Production\ProductionBundle\Entity\BackBusinessUnitTypes:
    type: entity
    table: back_business_unit_types
    id:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        active:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
