Production\ProductionBundle\Entity\PurchaseProposalDetall:
    type: entity
    table: purchase_proposal_detall
    id:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: AUTO
    fields:
        detailId:
            type: integer
            unsigned: true
            nullable: false
            column: detail_id
        sizeSort:
            type: integer
            unsigned: true
            nullable: false
            column: size_sort
        cantidad:
            type: integer
            unsigned: false
            nullable: false
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        purchaseProposal:
            targetEntity: PurchaseProposal
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                purchase_proposal_id:
                    referencedColumnName: id
            orphanRemoval: false
        backModels:
            targetEntity: BackModels
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                back_models_id:
                    referencedColumnName: id
            orphanRemoval: false
        backColors:
            targetEntity: BackColors
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                back_colors_id:
                    referencedColumnName: id
            orphanRemoval: false
        backSizes:
            targetEntity: BackSizes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                back_sizes_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
