BackColors:
    type: entity
    table: back_colors
    id:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        code:
            type: string
            length: 255
            fixed: false
            nullable: false
        image:
            type: string
            length: 255
            fixed: false
            nullable: true
        rgb:
            type: string
            length: 6
            fixed: false
            nullable: false
        active:
            type: boolean
            nullable: true
        sort:
            type: boolean
            nullable: true
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToMany:
        model:
            targetEntity: BackModels
            cascade: {  }
            mappedBy: color
            inversedBy: null
            joinTable: null
            orderBy: null
    manyToOne:
        backGroupsColor:
            targetEntity: BackGroupsColors
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                back_groups_color_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
