ProdOrdersHasPrices:
    type: entity
    table: prod_orders_has_prices
    id:
        prodOrdersHasPricesId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: prod_orders_has_prices_id
            generator:
                strategy: AUTO
    fields:
        total:
            type: decimal
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        prodPrice:
            targetEntity: ProdPrices
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                prod_price_id:
                    referencedColumnName: id
            orphanRemoval: false
        prodOrder:
            targetEntity: ProdOrders
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                prod_order_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
