ProdOrdersComments:
    type: entity
    table: prod_orders_comments
    id:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    fields:
        comment:
            type: text
            nullable: true
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        backUser:
            targetEntity: BackUsersOld
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                back_user_id:
                    referencedColumnName: id
            orphanRemoval: false
        prodOrder:
            targetEntity: ProdOrders
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                prod_order_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
